import 'package:flutter/material.dart';

ColorScheme colorScheme = const ColorScheme(
  background: Color.fromRGBO(22, 36, 79, 1),
  brightness: Brightness.light,
  error: Colors.red,
  errorContainer: null,
  onError: Colors.red,
  onErrorContainer: null,
  inversePrimary: null,
  inverseSurface: null,
  onBackground: Color.fromRGBO(34, 45, 81, 1),
  onPrimary: Colors.white,
  onPrimaryContainer: null,
  onSecondary: Colors.red,
  onSecondaryContainer: null,
  onSurface: Colors.white,
  onSurfaceVariant: null,
  onTertiary: Color.fromRGBO(148, 163, 184, 1),
  onTertiaryContainer: null,
  outline: null,
  outlineVariant: Color.fromRGBO(34, 45, 81, 1),
  primary: Color.fromRGBO(11, 19, 43, 1),
  primaryContainer: Color.fromRGBO(21, 32, 63, 1),
  secondary: Color.fromRGBO(17, 27, 57, 1),
  secondaryContainer: null,
  scrim: null,
  shadow: null,
  surface: Color.fromRGBO(11, 19, 43, 1),
  surfaceTint: null,
  surfaceVariant: null,
  tertiary: null,
  tertiaryContainer: null,
);
