name: indigo_insights
description: "Indigo Insights for the Indigo community made by PWG."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1
  flutter: 3.32.4

dependencies:
  collection: ^1.19.1
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_hooks: ^0.21.2
  flutter_launcher_icons: ^0.14.3
  hooks_riverpod: ^2.6.1
  http: ^1.4.0
  intl: ^0.20.2
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

flutter_launcher_icons:
  android: true

  ios: true
  remove_alpha_ios: true

  image_path: "assets/icons/ic_launcher.png"
  adaptive_icon_background: "assets/icons/ic_launcher_background.png"
  adaptive_icon_foreground: "assets/icons/ic_launcher_foreground.png"
  adaptive_icon_monochrome: "assets/icons/ic_launcher_monochrome.png"

  web:
    generate: true

  windows:
    generate: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/

  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Light.ttf
          weight: 300
        - asset: fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: fonts/Quicksand-Bold.ttf
          weight: 700
